config/routes.rb
Tfpullrequests::Application.routes.draw do
  match '/404', :to => 'errors#not_found'
  match '/422', :to => 'errors#unprocessable'
  match '/500', :to => 'errors#internal'

  resources :gifts
  resources :users
  resources :projects, :only => [:index, :new, :create]
  resources :pull_requests, :only => [:index]
  resource  :dashboard do 
    member do
      get :delete
      delete :destroy
    end
  end
  resource  :pull_request_download, :only => :create

  match '/preferences', :to => 'dashboards#preferences', :as => 'preferences'
  match '/preferences/update', :to => 'dashboards#update_preferences', :as => 'update_preferences'

  match '/login',  :to => 'sessions#new',     :as => 'login'
  match '/logout', :to => 'sessions#destroy', :as => 'logout'

  match '/auth/twitter/callback',   :to => 'twitter#authorize'
  delete '/twitter/remove',         :to => 'twitter#remove'

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure',            :to => 'sessions#failure'

  match 'about', :to => 'static#about'
  match 'api', :to => 'static#api'
  match 'contributing', :to => 'static#contributing'

  root :to => 'static#homepage'

  match '/email' => redirect('/preferences') # old preferences URL

  match '/:id' => redirect('/users/%{id}') # User public vanity url, must be lowest priority
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :uid, :provider, :nickname, :email, :gravatar_id, :token, :email_frequency, :skills_attributes, :twitter_token

  attr_writer :gift_factory

  has_many :pull_requests, :dependent => :destroy
  has_many :skills,        :dependent => :destroy
  has_many :gifts,         :dependent => :destroy

  paginates_per 99

  accepts_nested_attributes_for :skills, :reject_if => proc { |attributes| !Project::LANGUAGES.include?(attributes['language']) }

  after_create :download_pull_requests, :estimate_skills

  validates_presence_of :email, :if => :send_regular_emails?
  validates_format_of :email, :with => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/, :allow_blank => true, :on => :update

  def self.find_by_nickname!(nickname)
    where(['lower(nickname) =?', nickname.downcase]).first!
  end

  def self.create_from_auth_hash(hash)
    create!(extract_info(hash))
  end

  def self.find_by_auth_hash(hash)
    conditions = extract_info(hash).slice(:provider, :uid)
    where(conditions).first
  end

  def self.collaborators
    collabs = Rails.configuration.collaborators
    return [] if collabs.nil?
    collaborators = collabs.map(&:login)
    result = where('nickname in (?)', collaborators)
    collaborators.map { |c| result.find { |u| u.nickname == c } }
  end

  def authorize_twitter!(nickname, token, secret)
    self.twitter_nickname = nickname
    self.twitter_token    = token
    self.twitter_secret   = secret
    self.save!
  end

  def remove_twitter!
    self.twitter_nickname = nil
    self.twitter_token    = nil
    self.twitter_secret   = nil
    self.save!
  end

  def twitter_linked?
    twitter_token.present? && twitter_secret.present?
  end

  def twitter_profile
    "https://twitter.com/#{twitter_nickname}" if twitter_nickname.present?
  end

  def github_profile
    "https://github.com/#{nickname}" if nickname.present?
  end

  def suggested_projects
    Project.where(:main_language => languages).not_owner(nickname)
  end

  def estimate_skills
    if ENV['GITHUB_KEY'].present?
      languages = github_client.repos.map(&:language).uniq.compact
      (Project::LANGUAGES & languages).each do |language|
        skills.create(:language => language)
      end
    end
  end

  def languages
    skills.any? ? skills.order(:language).pluck(:language) : Project::LANGUAGES
  end

  def github_client
    @github_client ||= Octokit::Client.new(:login => nickname, :oauth_token => token, :auto_traversal => true)
  end

  def send_notification_email
    if send_daily?
      ReminderMailer.daily(self).deliver
    elsif send_weekly?
      ReminderMailer.weekly(self).deliver
    else
      return
    end
    update_attribute(:last_sent_at, Time.now.utc)
  end

  def send_daily?
    if email_frequency == 'daily'
      last_sent_at.nil? || last_sent_at < 23.hours.ago
    end
  end

  def send_weekly?
    if email_frequency == 'weekly'
      last_sent_at.nil? || last_sent_at < (6.days + 23.hours).ago
    end
  end

  def new_gift(attrs={})
    gift = gift_factory.call(attrs)
    gift.date ||= closest_free_gift_date
    gift.user = self
    gift
  end

  def gift_for(date)
    Gift.find(id, date)
  end

  def send_regular_emails?
    ['daily', 'weekly'].include? email_frequency
  end

  def to_param
    nickname
  end

  def download_pull_requests
    pull_request_downloader.pull_requests.each do |pr|
      pull_requests.create_from_github(pr) unless pull_requests.find_by_issue_url(pr['payload']['pull_request']['issue_url'])
    end
  end

  def twitter
    @twitter ||= Twitter::Client.new(
      :consumer_key       => ENV['TWITTER_KEY'],
      :consumer_secret    => ENV['TWITTER_SECRET'],
      :oauth_token        => twitter_token,
      :oauth_token_secret => twitter_secret
    )
  end

  def unspent_pull_requests
    gifted_pull_requests = gifts.map {|g| g.pull_request }
    pull_requests.reject{|pr| gifted_pull_requests.include?(pr) }
  end

  def closest_free_gift_date
    last_gift = self.gifts.last
    last_gift.nil? ? PullRequest::EARLIEST_PULL_DATE : last_gift.date + 1.day
  end

  private
  def pull_request_downloader
    Rails.application.config.pull_request_downloader.call(nickname, token)
  end

  def self.extract_info(hash)
    provider    = hash.fetch('provider')
    uid         = hash.fetch('uid')
    nickname    = hash.fetch('info',{}).fetch('nickname')
    email       = hash.fetch('info',{}).fetch('email', nil)
    gravatar_id = hash.fetch('extra',{}).fetch('raw_info',{}).fetch('gravatar_id', nil)
    token       = hash.fetch('credentials', {}).fetch('token')

    {
      :provider => provider,
      :token => token,
      :uid => uid,
      :nickname => nickname,
      :email => email,
      :gravatar_id => gravatar_id
    }
  end

  def gift_factory
    @gift_factory ||= Gift.public_method(:new)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html, :json

  def index
    @users = User.order('pull_requests_count desc').includes(:pull_requests).page params[:page]
    respond_with @users
  end

  def show
    @user      = User.find_by_nickname!(params[:id])
    @calendar  = Calendar.new(Gift.giftable_dates, @user.gifts)
    respond_with @user
  end
end

app/views/users/_calendar.html.haml
.calendar
  %ol.unstyled.clearfix.calendar-inner
    - 1.upto(calendar.start_padding) do
      %li.calendar-day.calendar-padding

    - calendar.each_day do |date, gift|
      %li.calendar-day
        .calendar-inner
          %span{ :class => date == Date.today ? 'calendar-mday calendar-mday-today' : 'calendar-mday' }
            = date.mday
          - if gift.present? && gift.user == current_user
            %small
              = link_to "x", gift_path(gift), :title => "Remove gift", :method => :delete, "data-confirm" => "Remove this gift?"
          %p.large
            = link_to gift.pull_request_title, gift.pull_request_issue_url, :target => :blank if gift.present?
          %p.small
            = link_to gift.pull_request_title, gift.pull_request_issue_url, :target => :blank if gift.present?

    %li.calendar-day.calendar-christmas
      .calendar-inner
        %span.calendar-mday 25
        %h4 Merry Christmas

app/views/users/_user.html.haml
%li.user
  = link_to image_tag(gravatar_url(user.gravatar_id), :width => 80, :height => 80, :alt =>user.nickname), user.nickname, rel: 'tooltip', data: { original_title: "#{user.nickname} - #{user.pull_requests_count} pull requests." }

app/views/users/index.html.haml
#users.row-fluid.clearfix
  .span12
    %h3
      = User.count
      Developers already involved

    %ul.clearfix
      = render @users

= paginate @users

app/views/users/show.html.haml
.row-fluid
  .span10
    %h2
      #{@user.nickname}
    .row-fluid.clearfix.social-buttons
      .span4
        = github_button @user.nickname
      - if @user.twitter_nickname.present?
        .span6
          %a{:href => "https://twitter.com/#{@user.twitter_nickname}", :class => 'twitter-follow-button'}
            Follow
            @#{@user.twitter_nickname}
          :javascript
            !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");

    - if @user.skills.any?
      %h4 Preferred Languages
      = @user.languages.to_sentence

  .span2
    .avatar= image_tag(gravatar_url(@user.gravatar_id, 100), :width => 100, :alt => @user.nickname)

.row-fluid
  .span12

    %h3 24 Pull Requests
    %h4
      =@user.nickname
      has made
      =@user.pull_requests.count
      total pull requests so far.
    = render :partial => 'calendar', :object => @calendar

.row-fluid
  %h3 Coderwall Badges
  #coderwall-content{:data => {:nickname => "#{@user.nickname}"}}