config/routes.rb
Tfpullrequests::Application.routes.draw do
  match '/404', :to => 'errors#not_found'
  match '/422', :to => 'errors#unprocessable'
  match '/500', :to => 'errors#internal'

  resources :gifts
  resources :users
  resources :projects, :only => [:index, :new, :create]
  resources :pull_requests, :only => [:index]
  resource  :dashboard do 
    member do
      get :delete
      delete :destroy
    end
  end
  resource  :pull_request_download, :only => :create

  match '/preferences', :to => 'dashboards#preferences', :as => 'preferences'
  match '/preferences/update', :to => 'dashboards#update_preferences', :as => 'update_preferences'

  match '/login',  :to => 'sessions#new',     :as => 'login'
  match '/logout', :to => 'sessions#destroy', :as => 'logout'

  match '/auth/twitter/callback',   :to => 'twitter#authorize'
  delete '/twitter/remove',         :to => 'twitter#remove'

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure',            :to => 'sessions#failure'

  match 'about', :to => 'static#about'
  match 'api', :to => 'static#api'
  match 'contributing', :to => 'static#contributing'

  root :to => 'static#homepage'

  match '/email' => redirect('/preferences') # old preferences URL

  match '/:id' => redirect('/users/%{id}') # User public vanity url, must be lowest priority
end

app/models/gift.rb
class Gift < ActiveRecord::Base
  attr_accessible :user, :pull_request, :date

  class << self
    attr_writer :default_date
  end

  belongs_to :user
  belongs_to :pull_request

  validates :user, :presence => true
  validates :pull_request, :presence => true
  validates :date, :presence => true,
                   :uniqueness => { :scope => :user_id,
                                    :message => "you only need one gift per day. Save it for tomorrow!" },
                   :inclusion => { :in => proc { Gift.giftable_dates },
                                   :message => "your gift should be for the month of December." }

  delegate :title, :issue_url, :to => :pull_request, :prefix => true

  after_initialize do
    self.date ||= Gift.default_date
  end

  def self.find(user_id, date)
    where(:user_id => user_id, :date => date).first
  end

  def self.giftable_dates
    1.upto(24).map { |day| Date.new(2012,12,day) }
  end

  def self.default_date
    @default_date ||= -> { Time.zone.now.to_date }
    @default_date.call
  end

  def to_param
    date.to_s
  end
end

app/models/gift_form.rb
class GiftForm
  attr_reader :gift

  def initialize(args={})
    @gift = args.fetch(:gift)
    @giftable_dates = args.fetch(:giftable_dates, [])
    @pull_requests = args.fetch(:pull_requests)
    @gift.date = args.fetch(:date) if args.fetch(:date, nil)
  end

  def pull_requests_for_select
    @pull_requests.sort{ |pr1, pr2| pr2.gifted_state <=> pr1.gifted_state }.map{ |pr|
      ["#{pr.gifted_state.to_s.humanize}: #{pr.repo_name} - #{pr.title}", pr.to_param]
    }
  end

  def giftable_dates
    @giftable_dates.map { |date|
      ["#{ date.strftime('%B') } #{ date.mday.ordinalize }", date.to_s]
    }
  end

  def show_date_select?
    !@giftable_dates.empty?
  end
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_filter :ensure_logged_in

  def index
    calendar  = Calendar.new(Gift.giftable_dates, current_user.gifts)

    render :index, :locals => { :calendar  => calendar }
  end

  def new
    gift_form = GiftForm.new(:gift           => current_user.new_gift,
                             :pull_requests  => current_user.unspent_pull_requests,
                             :giftable_dates => Gift.giftable_dates,
                             :date => params[:date])

    render :new, :locals => { :gift_form => gift_form }
  end

  def create
    gift = current_user.new_gift(gift_params)

    if gift.save
      gift_given
    else
      gift_failed(gift)
    end
  end

  def edit
    gift_form = GiftForm.new(:gift => gift,
                             :pull_requests => current_user.pull_requests)

    render :new, :locals => { :gift_form => gift_form }
  end


  def update
    if gift.update_attributes(gift_params)
      gift_given
    else
      gift_failed(gift)
    end
  end

  def destroy
    gift.destroy

    redirect_to user_path(current_user), :alert => "Gift removed"
  end

  private

  def gift
    @gift ||= current_user.gift_for(params[:id])
  end

  def gift_params
    pull_request = current_user.pull_requests.find_by_id(pull_request_id)
    post_params.merge(:pull_request => pull_request)
  end

  def gift_given
    flash[:notice] = "Your code has been gifted."
    redirect_to gifts_path()
  end

  def gift_failed(gift)
    gift_form = GiftForm.new(:gift => gift,
                             :pull_requests => current_user.pull_requests,
                             :giftable_dates => Gift.giftable_dates)

    render :new, :locals => { :gift_form => gift_form }
  end

  def pull_request_id
    params[:gift][:pull_request_id]
  end

  def post_params
    params[:gift].slice(:date)
  end
end

app/views/gifts/_form.html.haml
= simple_form_for gift_form.gift, :html => {:class => 'form-horizontal'}  do |form|

  - if gift_form.giftable_dates.any?
    = form.input :date, :collection => gift_form.giftable_dates

  = form.input :pull_request_id, :collection => gift_form.pull_requests_for_select

  .control-group
    .controls
      = form.button :submit, 'Gift it!'

app/views/gifts/_mini_form.html.haml
= simple_form_for gift_form.gift, :html => { :class => 'form-inline' }  do |form|
  = form.select :pull_request_id, gift_form.pull_requests_for_select
  = form.button :submit, 'Gift it!'

app/views/gifts/index.html.haml
%h2 Gifted Code

%p Here you can manage your pull requests and select &amp; curate your own set of "24 Pull Requests".

%p All your gifts will be shown on your #{ link_to 'public calendar', current_user.nickname }.

%table.table.table-striped.table-condensed.table-hover#gifts
  .tbody
    - calendar.each_day do |date, gift|
      %tr
        %td
          %strong= "#{ date.strftime('%B') } #{ date.mday.ordinalize }"
        %td
          - if gift
            = link_to gift.pull_request_title, gift.pull_request_issue_url
            = link_to 'Change', edit_gift_path(gift), :class => 'btn btn-small pull-right'
          - else
            Nothing gifted yet.
            = link_to 'Change', new_gift_path(:date => date), :class => 'btn btn-small pull-right'

app/views/gifts/new.html.haml
%h2
  Gifted Code
  %small Gift something meaningful to a project you love

= render :partial => 'form', :locals => { :gift_form => gift_form }