config/routes.rb
Tfpullrequests::Application.routes.draw do
  match '/404', :to => 'errors#not_found'
  match '/422', :to => 'errors#unprocessable'
  match '/500', :to => 'errors#internal'

  resources :gifts
  resources :users
  resources :projects, :only => [:index, :new, :create]
  resources :pull_requests, :only => [:index]
  resource  :dashboard do 
    member do
      get :delete
      delete :destroy
    end
  end
  resource  :pull_request_download, :only => :create

  match '/preferences', :to => 'dashboards#preferences', :as => 'preferences'
  match '/preferences/update', :to => 'dashboards#update_preferences', :as => 'update_preferences'

  match '/login',  :to => 'sessions#new',     :as => 'login'
  match '/logout', :to => 'sessions#destroy', :as => 'logout'

  match '/auth/twitter/callback',   :to => 'twitter#authorize'
  delete '/twitter/remove',         :to => 'twitter#remove'

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure',            :to => 'sessions#failure'

  match 'about', :to => 'static#about'
  match 'api', :to => 'static#api'
  match 'contributing', :to => 'static#contributing'

  root :to => 'static#homepage'

  match '/email' => redirect('/preferences') # old preferences URL

  match '/:id' => redirect('/users/%{id}') # User public vanity url, must be lowest priority
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_filter :ensure_logged_in
  before_filter :set_email_preferences, :except => [:preferences, :update_preferences]

  def show
    pull_requests = current_user.pull_requests.order('created_at desc')
    projects      = current_user.suggested_projects.limit(100).sample(12).sort_by(&:name)
    gifted_today  = current_user.gift_for(Time.zone.now.to_date)

    if is_decemeber? && current_user.pull_requests.any? && !current_user.gift_for(today)
      gift      = current_user.new_gift
      gift_form = GiftForm.new(:gift => gift, :pull_requests => current_user.unspent_pull_requests)
    end

    render :show, :locals => { :user => current_user,
                               :pull_requests => pull_requests,
                               :projects => projects,
                               :gift_form => gift_form }
  end

  def update_preferences
    current_user.skills.delete_all
    if current_user.update_attributes(params[:user])
      redirect_to dashboard_path
    else
      render :preferences
    end
  end

  def destroy
    current_user.destroy
    session.delete(:user_id)
    flash[:notice] = "Your account was successfully deleted"
    redirect_to root_path
  end

  protected
  def today
    Time.zone.now.to_date
  end

  def is_decemeber?
    today > Date.new(2012,12,1)
  end

  def set_email_preferences
    redirect_to preferences_path unless current_user.email_frequency.present?
  end
end

app/views/dashboards/_pull_requests_if_any.html.haml
- if current_user.pull_requests.length > 0
  = render :partial => 'pull_requests/pull_request', :collection => pull_requests
- else
  %p You've not sent any pull requests, what are you waiting for?!

app/views/dashboards/delete.html.haml
%h1 Delete your account

%p We just wanted to check that you really do wish to delete your account, this will remove your profile and all pull requests from the site, although any suggested projects will remain.

%p
  If you simply want to stop recieving email notifications you can change your #{link_to 'email preferences', preferences_path}.

%p
  = link_to 'Confirm Deletion', dashboard_path, :method => :delete, :class => 'btn'
  or
  = link_to 'I changed my mind, take me back!', dashboard_path

app/views/dashboards/preferences.html.haml
%h2 Set your Email Preferences 

%p At the frequency you choose, we'll send you helpful emails from now until the project is over, highlighting some suggested projects you might consider contributing to. As an added bonus, we'll take the liberty of personalizing our suggestions to your language proficiency based on the repos in your GitHub profile. Alternatively, you can choose your languages below.

- if current_user.email_frequency.present?
  %small= link_to 'Want to delete your account?', delete_dashboard_path, :class => 'pull-right'

%p 
  %em You can always change your email preferences later.

= simple_form_for current_user, :url => update_preferences_path, :html => {:class => 'form-horizontal'}  do |form|
  = form.input :email
  = form.input :email_frequency, :collection => [['Never', 'none'], ['Daily', 'daily'], ['Weekly', 'weekly']], :selected => (form.object.email_frequency || 'daily')
  - if current_user.twitter_linked?
    .control-group
      %label.control-label Twitter Account
      .controls
        = link_to "@#{current_user.twitter_nickname}", "https://twitter.com/#{current_user.twitter_nickname}", target: '_blank'
        = link_to '<i class="icon-twitter"></i> Remove Account'.html_safe, twitter_remove_path, method: :delete, class: 'btn btn-danger'

  %h3 Which languages do you know?
  #skills.clearfix
    = form.simple_fields_for :skills, Project::LANGUAGES.map{|l| Skill.new(:language => l)} do |skill_form|
      - language = skill_form.object.language
      .control-group.string
        %label.control-label{:for => language}= language
        .controls
          = skill_form.check_box :language, {:id => language, :checked => current_user.skills.map(&:language).include?(language)}, language

  .control-group
    .controls
      = form.button :submit, 'Save and Continue'

app/views/dashboards/show.html.haml
%h2
  Welcome back, #{user.nickname}

%p This is where you can see all the activity we've tracked for you in the run up to Christmas.

%hr

- if gift_form
  Looks like you haven't gifted any code today. Would you like to gift
  = render :partial => 'gifts/mini_form', :locals => { :gift_form => gift_form }
  %hr

= link_to "<i class='icon-twitter'></i> #{I18n.t 'twitter.link_account.text'}".html_safe, '/auth/twitter', :class => 'btn btn-info pull-right',
  rel: 'tooltip', title: I18n.t('twitter.link_account.tooltip') unless current_user.twitter_linked?
= link_to 'Synchronize Pull Requests', pull_request_download_path, :id => 'fetch-pull-requests', :class => 'btn pull-right', :rel => 'tooltip', :title => I18n.t('pull_request.download.tooltip')

#spinner
  = image_tag "spinner.gif", :class => 'pull-right'

%h3
  Your Pull Requests

%div#pull-requests.clearfix
  = render :partial => 'pull_requests_if_any', :locals => { :pull_requests => pull_requests }

%hr
.row-fluid.clearfix
  .span12
    %h3
      Suggested Projects
      = link_to 'Suggest a project', new_project_path, :class => 'btn pull-right'
      = link_to 'View All', projects_path, :class => 'btn pull-right'
    %p
      Can't think of a project you would like to help out? We've put together a list of popular projects:

  #projects
    = render projects