config/routes.rb
Tfpullrequests::Application.routes.draw do
  match '/404', :to => 'errors#not_found'
  match '/422', :to => 'errors#unprocessable'
  match '/500', :to => 'errors#internal'

  resources :gifts
  resources :users
  resources :projects, :only => [:index, :new, :create]
  resources :pull_requests, :only => [:index]
  resource  :dashboard do 
    member do
      get :delete
      delete :destroy
    end
  end
  resource  :pull_request_download, :only => :create

  match '/preferences', :to => 'dashboards#preferences', :as => 'preferences'
  match '/preferences/update', :to => 'dashboards#update_preferences', :as => 'update_preferences'

  match '/login',  :to => 'sessions#new',     :as => 'login'
  match '/logout', :to => 'sessions#destroy', :as => 'logout'

  match '/auth/twitter/callback',   :to => 'twitter#authorize'
  delete '/twitter/remove',         :to => 'twitter#remove'

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure',            :to => 'sessions#failure'

  match 'about', :to => 'static#about'
  match 'api', :to => 'static#api'
  match 'contributing', :to => 'static#contributing'

  root :to => 'static#homepage'

  match '/email' => redirect('/preferences') # old preferences URL

  match '/:id' => redirect('/users/%{id}') # User public vanity url, must be lowest priority
end

app/views/layouts/application.html.haml
!!!
%html{ :lang => 'en', :"xmlnsns:og" => 'http://ogp.me/ns#', :"xmlns:fb" => 'http://http://www.facebook.com/2008/fbml' }
  %head
    
    / Facebook open graph api
    %meta{ :property => 'og:title', :content => '24 Pull Requests' }
    %meta{ :property => 'og:type', :content => 'website' }
    %meta{ :property => 'og:url', :content => 'http://24pullrequests.com/' }
    %meta{ :property => 'og:image', :content => "#{root_url}#{image_path('24pr-logo.jpg')}" } 
    %meta{ :property => 'og:description', :content => "24 Pull Requests is a yearly initiative to encourage developers around the world to send a pull request every day in December up to Christmas." } 

    
    %meta{ :charset => "utf-8" }
    %meta{ :'http-equiv' => 'X-UA-Compatible', :content => "IE=Edge,chrome=1" }
    %meta{ :name => "viewport", :content => "user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0"  }
    %title= content_for?(:title) ? yield(:title) : "24 Pull Requests"
    = csrf_meta_tags

    :plain
      <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
      <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
      <![endif]-->

    = stylesheet_link_tag "application", :media => "all"

    /  For third-generation iPad with high-resolution Retina display:
    /  Size should be 144 x 144 pixels
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'

    / For iPhone with high-resolution Retina display:
    / Size should be 114 x 114 pixels
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'

    / For first- and second-generation iPad:
    / Size should be 72 x 72 pixels
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'

    / For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    / Size should be 57 x 57 pixels
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'

    / For all other devices
    / Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
  %body
    = content_for :body_open unless content_for(:body_open).nil?

    %a.forkme{ :href => "https://github.com/andrew/24pullrequests", :target => '_blank'}
      %img{ :src => 'https://s3.amazonaws.com/github/ribbons/forkme_right_white_ffffff.png', :alt => 'Fork me on GitHub'}


    .hb.header-background
      .hb.header-background-2
        .hb.header-background-3

    %header
      .bar
      .logo
        = link_to 'homepage', root_path

      - if params[:action] == 'homepage'
        .tagline.hidden-phone

      = render :partial => 'user_nav'

    %article
      .container-fluid
        .row-fluid
          .alert.alert-info
            %h3 24 Pull Requests has finished for this year
            %p
              Over the past 24 days,
              %strong= PullRequest.all.map(&:user_id).uniq.length
              developers have submitted
              %strong= PullRequest.count
              pull requests to
              %strong= PullRequest.select(:repo_name).map(&:repo_name).uniq.count
              different open source projects.

            %p Merry Christmas and see you all next year when we do it all again!
            %hr
            %p Still want to help out with open source projects? Check out these other great initiatives:

            %h4= link_to 'CodeTriage', 'http://www.codetriage.com/'
            
            %p Give back to open source, one issue at a time, with CodeTriage. You'll get one issue from your favorite repo per day to help you dig deeper, learn more, and stay involved with the code you rely on.
            
            %h4= link_to 'ContribHub', 'http://contribhub.co/'
            
            %p Do you know you have a neighbor needing some help with a really cool project? With ContribHub you will!
            %p ContribHub is a GitHub-based application that makes it easier to find projects to contribute to and grow a community around it.
            
        .row-fluid
          .span12
            - if flash.any?
              .messages
                - if flash[:alert]
                  .alert= flash[:alert]
                - if flash[:notice]
                  .alert.alert-info= flash[:notice]
            = yield

  %footer
    .dark
      .dark-inner
        .logo.logo-dark
        %ul.unstyled.pull-right
          %li
            Sponsored by&nbsp;
            #{link_to 'DNSimple', 'http://dnsimple.com'}
            &nbsp;&amp;&nbsp;
            = link_to 'Heroku Postgres', 'http://postgres.heroku.com/'            
        %ul.unstyled.pull-left
          %li
            = link_to 'About', about_path
          %li
            = link_to 'How to contribute?', contributing_path
          %li
            = link_to 'API', api_path

    .ftw
      = link_to image_tag('humanstxt-isolated-blank.gif'), '/humans.txt'
      Open Source FTW!
      %strong 2012

    = javascript_include_tag "application"